config/routes.rb
Rails.application.routes.draw do
  
  resources :time_sheets, only: [:index, :new, :create]

  root :to=>"time_sheets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/time_sheet.rb
class TimeSheet < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/time_sheets_controller.rb
class TimeSheetsController < ApplicationController

  def index
		@time_sheets = TimeSheet.includes(:project).all
	end
	
	def new
  	@time_sheet = TimeSheet.new
  	@projects = Project.all
	end

	def create

  	projects = params[:projects]
  	times = params[:time]
 		descriptions = params[:description]

    time_sheets = []

    projects.each_with_index do |value, key|

      project_time = times[key]
      description = descriptions[key]

      time_sheet = TimeSheet.new

      time_sheet.project_id = value
      time_sheet.project_time = project_time
      time_sheet.description = description

      time_sheets << time_sheet
    end

    TimeSheet.import time_sheets

    redirect_to time_sheets_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_sheets_helper.rb
module TimeSheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SedinTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/time_sheets/index.html.erb
<div>
<table>
		<tr>
			<th>Project</th>
		    <th>Time</th>
		    <th>Description</th>
		</tr>
		<% @time_sheets.each do |t_s| %>
        <tr>
			<td><%= t_s.project.name %></td>
			<td><%= t_s.project_time %></td>
			<td><%= t_s.description %></td>
		</tr>
		<% end %>	
	</table>
	<%= link_to "new", new_time_sheet_path %>	
</div>	

app/views/time_sheets/new.html.erb
<button class="btn btn-primary" name="button" id = "add" type="submit">
 Add
</button>
<br><br>

<%= form_for @time_sheet do |f| %>
	<div id="buildyourform">
	</div>
	<br><br>
	<%= f.submit 'Save Entries', id: "save" %>
<% end %>
<script>

$(document).ready(function() {

  $("#save").hide();
  $("#add").click(function() {
    var lastField = $("#buildyourform div:last");
    var intId = (lastField && lastField.length && lastField.data("idx") + 1) || 1;
    var fieldWrapper = $("<div class=\"fieldwrapper\" id=\"field" + intId + "\"/>");
    fieldWrapper.data("idx", intId);
    var projects = '<option value=""> Select </option>';
    <% @projects.each do |obj| %>
      projects += '<option value="<%= obj.id %>"> <%= obj.name %> </option>';
    <% end %>
    var time = $("<input class = \"datetimepicker\" name=\"time[]\" />");
    var description = $("<input type=\"text\" name=\"description[]\" />");
    var removeButton = $("<input type=\"button\" class=\"remove\" value=\"x\" />");
    removeButton.click(function() {
      $(this).parent().remove();
    });
    fieldWrapper.append('<select name = "projects[]">'+projects+'</select>');
    fieldWrapper.append(time);
    fieldWrapper.append(description);
    fieldWrapper.append(removeButton);
    $("#buildyourform").append(fieldWrapper);
    $("#save").show();
  });
});
  
</script>